const fs=require('fs');const path=require('path');const root=process.cwd(),out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});for(const f of ['index.html','favicon.svg','favicon.ico','robots.txt','site.webmanifest','sitemap.xml','schema.jsonld']){const s=path.join(root,f);if(fs.existsSync(s))fs.copyFileSync(s,path.join(out,f));}fs.cpSync(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});let h=fs.readFileSync(path.join(out,'index.html'),'utf8');
const rep=(a,b,n)=>{if(!h.includes(a))throw new Error('v10 missing '+n);h=h.replace(a,b)};
rep('<span class="brand-mark">PD</span>','<span class="brand-mark shield"><img src="/assets/propdata-shield-mark.svg" alt="PropData shield"></span>','header shield');h=h.replace('<span class="brand-mark">PD</span>','<span class="brand-mark shield"><img src="/assets/propdata-shield-mark.svg" alt="PropData shield"></span>');
h=h.replace(/https:\/\/images\.unsplash\.com\/photo-1770064319727[^"']*/g,'/assets/global-network-v10.svg');
h=h.replace(/https:\/\/propdata\.proptechusa\.ai\/images\/new-zealand-parcels\.png/g,'/assets/country-nz.svg');
h=h.replace(/https:\/\/propdata\.proptechusa\.ai\/images\/property-infrastructure\.webp/g,'/assets/country-us.svg');
h=h.replace(/https:\/\/images\.unsplash\.com\/photo-1779991672998[^"']*/g,'/assets/country-gb.svg');
h=h.replace(/https:\/\/upload\.wikimedia\.org\/wikipedia\/commons\/7\/7d\/Aerial_view_of_Sydney_Harbour\.jpg/g,'/assets/country-au.svg');
h=h.replace(/https:\/\/images\.unsplash\.com\/photo-1760097776531[^"']*/g,'/assets/country-ee.svg');
h=h.replace(/https:\/\/images\.unsplash\.com\/photo-1502602898657[^"']*/g,'/assets/country-fr.svg');
h=h.replace(/https:\/\/images\.unsplash\.com\/photo-1539037116277[^"']*/g,'/assets/country-es.svg');
const stores=[
['US','United States','COUNTY + STATE · PROPDATA','166M+','indexed parcel records','https://propdata.proptechusa.ai/','Starter|Build and evaluate|$79|10K req/mo|https://buy.stripe.com/7sYdR9c6ybuC7BHbQL7wA04','Builder|Production teams|$199|50K req/mo|https://buy.stripe.com/8x28wP7Qi8iq5tz4oj7wA02','Scale|Higher-volume use|$499|250K req/mo|https://buy.stripe.com/7sYfZh2vY2Y6cW10837wA0p'],
['GB','Great Britain','UPRN · OS · HMLR · INSPIRE','~40M','UPRN property identities','https://gb.proptechusa.ai/','Developer|Build and evaluate|£79|10K req/mo|https://buy.stripe.com/4gM8wP1rUfKS4pv5sn7wA0g','Builder|Production teams|£249|50K req/mo|https://buy.stripe.com/8x29ATgmOaqy4pvg717wA0h','Scale|Higher-volume use|£699|250K req/mo|https://buy.stripe.com/00w5kDfiK1U21djaMH7wA0i'],
['NZ','New Zealand','TOITŪ TE WHENUA LINZ','3.04M','primary parcels','https://nz.proptechusa.ai/','Developer|Build and evaluate|NZ$99|10K req/mo|https://buy.stripe.com/5kQ14neeGbuC09f0837wA0a','Builder|Production teams|NZ$299|50K req/mo|https://buy.stripe.com/6oU5kDgmO6aig8daMH7wA0b','Scale|Higher-volume use|NZ$799|250K req/mo|https://buy.stripe.com/3cIdR9daC9mu1djdYT7wA0c'],
['AU','Australia','G-NAF · STATE-NATIVE CADASTRE','16.97M','national G-NAF addresses','https://au.proptechusa.ai/','Developer|Build and evaluate|A$149|10K req/mo|https://buy.stripe.com/eVqcN53A256e6xD9ID7wA0d','Builder|Production teams|A$449|50K req/mo|https://buy.stripe.com/14A6oH9Yq6ai7BH0837wA0e','Scale|Higher-volume use|A$1,199|250K req/mo|https://buy.stripe.com/28E5kD9YqgOWg8d9ID7wA0f'],
['EE','Estonia','CADASTRE · ADS · EHR','778K+','land-enriched cadastral units','https://ee.proptechusa.ai/','Developer|Build and evaluate|€49|10K req/mo|https://buy.stripe.com/7sYaEXgmO42ag8d2gb7wA07','Builder|Production teams|€149|50K req/mo|https://buy.stripe.com/bJefZh0nQeGOaNTcUP7wA08','Scale|Higher-volume use|€399|250K req/mo|https://buy.stripe.com/eVq6oH3A256e3lr9ID7wA09'],
['FR','France','CADASTRE · BAN · RNB / TOPO · DVF','≈100M','official cadastral source-system scale','https://france.proptechusa.ai/','Developer|Build and evaluate|€79|10K req/mo|https://buy.stripe.com/9B66oH7QigOW2hn3kf7wA0m','Builder|Production teams|€249|50K req/mo|https://buy.stripe.com/8x2cN56Me0PYcW1f2X7wA0n','Scale|Higher-volume use|€699|250K req/mo|https://buy.stripe.com/28E7sL5Ia9mu2hnaMH7wA0o'],
['ES','Spain','DGC CATASTRO · CP · AD · BU','78.94M','official DGC cadastral records','https://spain.proptechusa.ai/','Developer|Build and evaluate|€79|10K req/mo|https://buy.stripe.com/4gM8wP9Yq42af49g717wA0j','Builder|Production teams|€249|50K req/mo|https://buy.stripe.com/00w8wP6Me6aie057Av7wA0k','Scale|Higher-volume use|€699|250K req/mo|https://buy.stripe.com/dRmaEX0nQbuC3lr5sn7wA0l']];
const cards=stores.map(s=>{const plans=s.slice(6).map((x,i)=>{const[p,d,price,req,url]=x.split('|');return `<article class="all-plan${i===1?' featured':''}">${i===1?'<span class="all-badge">POPULAR</span>':''}<small>PROPDATA ${s[0]}</small><h4>${p}</h4><p>${d}</p><strong>${price}<em>/mo</em></strong><span>${req}</span><a href="${url}" target="_blank" rel="noopener">Buy ${p} →</a></article>`}).join('');return `<section class="country-store" id="pricing-${s[0].toLowerCase()}"><header><div><b>${s[0]}</b><h3>${s[1]}</h3><span>${s[2]}</span></div><div class="store-metric"><strong>${s[3]}</strong><span>${s[4]}</span></div></header><div class="all-plans">${plans}</div><footer><a href="${s[5]}">Country product & coverage →</a></footer></section>`}).join('');
const access=`<section class="section access" id="access"><div class="shell"><div class="section-head"><div><div class="eyebrow">Self-serve country access</div><h2>Seven storefronts. <em>Every plan visible.</em></h2></div><p>No hidden market selector. Choose the country and tier that fits your workflow, with local-market currency and the same explicit coverage contract underneath.</p></div><div class="all-stores">${cards}</div><div class="access-fine"><span>Checkout is processed securely by Stripe. API-key provisioning follows the applicable PropData account workflow.</span><a href="#enterprise">Need multi-country, bulk, white-label or custom infrastructure? →</a></div></div></section>`;
h=h.replace(/<section class="section access" id="access">[\s\S]*?<section class="section graph-section" id="model">/,access+'<section class="section graph-section" id="model">');
h=h.replace(/const markets=\{[\s\S]*?renderMarket\('US'\);/,'');
const css=`<style>.brand-mark.shield{background:transparent;border:0;border-radius:0}.brand-mark.shield img{width:43px;height:47px}.all-stores{display:grid;gap:18px}.country-store{overflow:hidden;border:1px solid #cfc7b8;border-radius:4px 34px 4px 34px;background:#fbf8f0;box-shadow:0 18px 48px rgba(23,22,16,.055)}.country-store>header{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:end;padding:26px 28px;border-bottom:1px solid #d8d0c2;background:linear-gradient(110deg,#fbf8f0,#eee8dc)}.country-store header b{display:inline-grid;place-items:center;width:43px;height:43px;border-radius:50%;background:#15140f;color:#fff;font:900 9px var(--mono)}.country-store h3{display:inline-block;margin:0 0 0 14px;font-family:var(--serif);font-size:32px;font-weight:400;letter-spacing:-.04em}.country-store header>div>span{display:block;margin-top:9px;font:850 8px var(--mono);letter-spacing:.08em;color:#777165}.store-metric{text-align:right}.store-metric strong{display:block;font-family:var(--serif);font-size:34px;font-weight:400;line-height:1}.store-metric span{display:block;margin-top:5px;color:#777165;font-size:10px}.all-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:0}.all-plan{position:relative;padding:25px 28px;border-right:1px solid #ddd5c8;display:flex;flex-direction:column;min-height:275px}.all-plan:last-child{border-right:0}.all-plan.featured{background:#e7f0e9}.all-plan small{font:900 8px var(--mono);letter-spacing:.09em;color:#746f63}.all-plan h4{margin:19px 0 6px;font-family:var(--serif);font-size:28px;font-weight:400}.all-plan p{margin:0;color:#6c675d;font-size:12px}.all-plan>strong{display:block;margin-top:23px;font-family:var(--serif);font-size:40px;font-weight:400}.all-plan>strong em{font-family:var(--sans);font-size:10px;font-style:normal;color:#777165}.all-plan>span{margin-top:6px;font:850 8px var(--mono);color:#555147}.all-plan>a{margin-top:auto;padding:12px 14px;border-radius:999px;background:#15140f;color:#fff;text-align:center;font-size:11px;font-weight:850}.all-plan.featured>a{background:#0e6639}.all-badge{position:absolute;right:22px;top:20px;padding:5px 7px;border-radius:999px;background:#0e6639;color:#fff!important;font-size:6px!important}.country-store>footer{padding:13px 28px;border-top:1px solid #ddd5c8;text-align:right}.country-store>footer a{font-size:10px;font-weight:850}.access-fine{margin-top:22px}@media(max-width:760px){.country-store>header{grid-template-columns:1fr}.store-metric{text-align:left}.all-plans{grid-template-columns:1fr}.all-plan{border-right:0;border-bottom:1px solid #ddd5c8;min-height:235px}.all-plan:last-child{border-bottom:0}}</style>`;h=h.replace('</head>',css+'</head>');
fs.writeFileSync(path.join(out,'index.html'),h);for(const m of ['propdata-shield-mark.svg','global-network-v10.svg','pricing-us','pricing-gb','pricing-nz','pricing-au','pricing-ee','pricing-fr','pricing-es','Seven storefronts.','https://buy.stripe.com/dRmaEX0nQbuC3lr5sn7wA0l'])if(!h.includes(m))throw new Error('v10 validation missing '+m);console.log('PASS: PropData Global v10 full seven-country storefront built.');